version: '3.1'

volumes:
  portainer_data:
    driver: local

services:
  abc-mysql:
    image: "mysql:5.7.22"
    hostname: "abc-mysql"
    container_name: "abc-mysql"
    environment:
      - SERVICE_NAME=abc-mysql
      - MYSQL_DATABASE=colegio
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=rootpw
    volumes:
      - ./colegioV3.sql:/docker-entrypoint-initdb.d/model.sql:ro
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: ['--lower_case_table_names=1', '--general-log=1', '--general-log-file=/var/log/mysql/general-log.log']

    # winpty docker exec -ti abc-mysql tail -f /var/log/mysql/general-log.log
    # jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false

  abc-phpmyadmin:
    image: "phpmyadmin/phpmyadmin:4.7"
    hostname: "abc-phpmyadmin"
    container_name: "abc-phpmyadmin"
    environment:
      - SERVICE_NAME=abc-phpmyadmin
      - PMA_HOST=abc-mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpw
    ports:
      - "8081:80"
    depends_on:
      - abc-mysql
